# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pDffQ8B_sVbC8K-tG8G-w0_F8xFI50w5
"""

import random
import time

while(True):
  temp = 0;
  humidity = 0;
  temp = random.random()*100;
  humidity = random.random()*100;
  print(temp,'C ', humidity,'%')
  if(temp > 50):
    print('Alarm is on');
  time.sleep(2)